from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet


def create_pdf(
    filename,
    loan_amount,
    annual_income,
    interest_rate,
    grade,
    purpose,
    probability,
    recommendation,
    expected_loss
):

    styles = getSampleStyleSheet()

    pdf = SimpleDocTemplate(filename)

    elements = []

    elements.append(
        Paragraph("<b>CrediGuard AI</b>", styles["Title"])
    )

    elements.append(
        Paragraph("Loan Risk Assessment Report", styles["Heading2"])
    )

    elements.append(Spacer(1, 20))

    data = [

        ["Loan Amount", f"₹{loan_amount:,.0f}"],

        ["Annual Income", f"₹{annual_income:,.0f}"],

        ["Interest Rate", f"{interest_rate}%"],

        ["Grade", grade],

        ["Purpose", purpose],

        ["Probability of Default", f"{probability*100:.2f}%"],

        ["Recommendation", recommendation],

        ["Expected Loss", f"₹{expected_loss:,.0f}"]

    ]

    table = Table(data)

    table.setStyle(TableStyle([

        ('BACKGROUND',(0,0),(-1,0),colors.darkblue),

        ('TEXTCOLOR',(0,0),(-1,0),colors.white),

        ('GRID',(0,0),(-1,-1),1,colors.black),

        ('BACKGROUND',(0,1),(-1,-1),colors.beige),

        ('BOTTOMPADDING',(0,0),(-1,0),12),

    ]))

    elements.append(table)

    elements.append(Spacer(1,25))

    elements.append(

        Paragraph(

            "This report was automatically generated by "
            "<b>CrediGuard AI</b>.",

            styles["BodyText"]

        )

    )

    pdf.build(elements)